baseURL = "https://cary205.github.io/hugo-hello/"
languageCode = "en-us"
title = "hugo-hello"
theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"